### PR TITLE
Bugfixes + New/Edit Ad - client-side image resize #1276

### LINKED ISSUE #1361: Wrong has_images ad counter when publishing new ad
After posting a new ad with one image the has_images counter is set to 2 instead of 1.

### PR DESCRIPTION
**Pull request by oliverds**
* New/Edit Ad - client-side image resize #1276 (not yet implemented on yclas and premium themes)
* Removed ajax load on edit profile link
* Fix for notification on message reply
* has_images counter bugfix on publish new, closes #1361
* ajax captcha validation bugfix #1360

### CODE REVIEW

File: oc/classes/model/ad.php [hunk 1]
```diff
@@ -378,6 +378,40 @@ public function save_image($image)
     }
 
     /**
+     * save_base64_image upload images with given path
+     * 
+     * @param string $image [base64 encoded image]
+     * @return bool
+     */
+    public function save_base64_image($image)
```
Comment (neo22s) [inline oc/classes/model/ad.php]: check nudes pics and size etc...?

Comment (oliverds) [inline oc/classes/model/ad.php]: > check nudes pics and size etc...?

Size and format is validated but yes forgot nude pictures validation

Comment (neo22s) [inline oc/classes/model/ad.php]: No problem ;)
